# Generated by Django 3.0.5 on 2020-04-28 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiDatabase', '0002_auto_20200428_0149'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessRecords',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Webpage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('url', models.URLField(unique=True)),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiDatabase.Topic')),
            ],
        ),
        migrations.RemoveField(
            model_name='languages',
            name='city',
        ),
        migrations.DeleteModel(
            name='AccessCounts',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Languages',
        ),
        migrations.AddField(
            model_name='accessrecords',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiDatabase.Webpage'),
        ),
    ]
