# Generated by Django 3.0.5 on 2020-04-30 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apiDatabase', '0003_auto_20200428_0353'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c', models.IntegerField(default=0)),
                ('c_plus', models.IntegerField(default=0)),
                ('c_sharp', models.IntegerField(default=0)),
                ('dart', models.IntegerField(default=0)),
                ('go', models.IntegerField(default=0)),
                ('haskell', models.IntegerField(default=0)),
                ('html_css', models.IntegerField(default=0)),
                ('java', models.IntegerField(default=0)),
                ('javaScript', models.IntegerField(default=0)),
                ('kotlin', models.IntegerField(default=0)),
                ('matLab', models.IntegerField(default=0)),
                ('obj_c', models.IntegerField(default=0)),
                ('perl', models.IntegerField(default=0)),
                ('php', models.IntegerField(default=0)),
                ('python', models.IntegerField(default=0)),
                ('r', models.IntegerField(default=0)),
                ('ruby', models.IntegerField(default=0)),
                ('rust', models.IntegerField(default=0)),
                ('scala', models.IntegerField(default=0)),
                ('swift', models.IntegerField(default=0)),
                ('typeScript', models.IntegerField(default=0)),
                ('visual_basic', models.IntegerField(default=0)),
                ('asp_net', models.IntegerField(default=0)),
                ('angular', models.IntegerField(default=0)),
                ('bootstrap', models.IntegerField(default=0)),
                ('django', models.IntegerField(default=0)),
                ('ember', models.IntegerField(default=0)),
                ('flask', models.IntegerField(default=0)),
                ('laravel', models.IntegerField(default=0)),
                ('node_js', models.IntegerField(default=0)),
                ('rails', models.IntegerField(default=0)),
                ('react', models.IntegerField(default=0)),
                ('spring', models.IntegerField(default=0)),
                ('vue_js', models.IntegerField(default=0)),
                ('ms_sql', models.IntegerField(default=0)),
                ('mongoDB', models.IntegerField(default=0)),
                ('my_sql', models.IntegerField(default=0)),
                ('postGreSql', models.IntegerField(default=0)),
                ('redis', models.IntegerField(default=0)),
                ('sqlite', models.IntegerField(default=0)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiDatabase.City')),
            ],
        ),
        migrations.RemoveField(
            model_name='webpage',
            name='topic',
        ),
        migrations.DeleteModel(
            name='AccessRecords',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
        migrations.DeleteModel(
            name='Webpage',
        ),
    ]
